--琩高–场蔼キА场羱戈
--(挡狦ㄌ场キА羱戈经逼)


SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID,
S.DEPARTMENT_NAME, S."AVG_SALARY"
FROM EMPLOYEES E,

(
SELECT E.DEPARTMENT_ID,D.DEPARTMENT_NAME, ROUND(AVG(E.SALARY),0) "AVG_SALARY"
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY E.DEPARTMENT_ID,D.DEPARTMENT_NAME
)S

WHERE E.DEPARTMENT_ID = S.DEPARTMENT_ID
AND E.SALARY > S."AVG_SALARY"
ORDER BY S."AVG_SALARY" DESC , E.SALARY DESC;

--------------------------------------------------------------------------------

--SELECT *  FROM
--
--(
--SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID,
--D.DEPARTMENT_NAME, D."AVG_SALARY"
--FROM EMPLOYEES E ,
--)S,
--
----(
----SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID 
----FROM EMPLOYEES E
----)E,
--
--(
--SELECT E.DEPARTMENT_ID,D.DEPARTMENT_NAME, ROUND(AVG(E.SALARY),0) "AVG_SALARY"
--FROM EMPLOYEES E 
--INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--GROUP BY E.DEPARTMENT_ID,D.DEPARTMENT_NAME
--)D
--
--WHERE S.DEPARTMENT_ID = S.DEPARTMENT_ID
--AND S.SALARY > D."AVG_SALARY"
--ORDER BY D."AVG_SALARY" DESC , S.SALARY DESC;

--------------------------------------------------------------------------------

--SELECT *  FROM
--
--(
--  SELECT E.EMPLOYEE_ID, E.FIRST_NAME ,E.SALARY ,D.DEPARTMENT_ID,D.DEPARTMENT_NAME, "AVG_SALARY"
--  FROM EMPLOYEES E
--) A,
--
--(
--   SELECT  E.DEPARTMENT_ID,E.DEPARTMENT_NAME,ROUND(avg(E.salary),0) "AVG_SALARY"
--   FROM EMPLOYEES E
--   INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--   GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME
--   
--) F
--
--WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
--AND A.SALARY > F."AVG_SALARY"
--ordEr by F."AVG_SALARY" dEsc;

--SELECT *  FROM

--------------------------------------------------------------------------------

--(
--   SELECT EMPLOYEE_ID, FIRST_NAME ,SALARY ,DEPARTMENT_ID
--   FROM EMPLOYEES
--) E,
--(
--   SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS
--) D,
--(
--   SELECT E.EMPLOYEE_ID, E.FIRST_NAME ,E.SALARY,E.DEPARTMENT_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME, ROUND(avg(salary),0) "AVG_SALARY"
--   FROM EMPLOYEES E , DEPARTMENTS D
--   innEr join DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--   group by E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, D.DEPARTMENT_ID
--   
----   ORDER BY AVG(SALARY) DESC
--) A
--
--
--
--WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
--AND E.SALARY > A."AVG_SALARY"
--ORDER BY A."AVG_SALARY" dEsc;
--


--------------------------------------------------------------------------------

--SELECT  *  FROM 
--(
--   SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
--) G , 
--(
--   SELECT FK_GEOGRAPHY_ID, STORE_NAME 
--   FROM STORE_INFORMATION
--) S
--WHERE G.GEOGRAPHY_ID = S.FK_GEOGRAPHY_ID;
--
--
--SELECT L.COUNTRY_ID, L.STATE_PROVINCE, L.CITY, -- 1.┮(瓣產瑆カ)
--D.DEPARTMENT_ID, D.DEPARTMENT_NAME,            -- 2.场(场絪腹场嘿)
--E.EMPLOYEE_ID, E.FIRST_NAME,                   -- 3.场恨瞶(絪腹﹎)
--J.JOB_TITLE -- 戮嘿
--FROM DEPARTMENTS D 
--INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
--LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
--LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID;
--
---- 琩高
--SELECT SUM(S.SALES) 
--FROM STORE_INFORMATION S WHERE S.STORE_NAME IN (
--  -- ず琩高
--  SELECT S.STORE_NAME FROM STORE_INFORMATION S WHERE S.FK_GEOGRAPHY_ID = 2
--);
--
---- 闽琩高
---- 琩高
--SELECT SUM(S.SALES) FROM STORE_INFORMATION S WHERE S.FK_GEOGRAPHY_ID IN (
--    -- ず琩高
--    SELECT G.GEOGRAPHY_ID FROM GEOGRAPHY G WHERE G.GEOGRAPHY_ID  = S.FK_GEOGRAPHY_ID
--);
--
--
--SELECT  *  FROM (
--   SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
--) G , 
--(
--   SELECT FK_GEOGRAPHY_ID, STORE_NAME 
--   FROM STORE_INFORMATION
--) S
--WHERE G.GEOGRAPHY_ID = S.FK_GEOGRAPHY_ID;
--
--
--SELECT  *  FROM (
--   SELECT GEOGRAPHY_ID, REGION_NAME FROM GEOGRAPHY
--) G , STORE_INFORMATION S
--WHERE G.GEOGRAPHY_ID = S.FK_GEOGRAPHY_ID;
